@startuml
[Ledger Network] as C1
() " \n Link Protocol Interface" as Interf
[Link Protocol] as C2
[Interledger Protocol] as C3
[Interledger Transport Protocol/STREAM] as C4
[Simple Payment Setup Protocl/SPSP] as C5

C1 - Interf
Interf - C2
C2 - C3
C3 ..> C4 : use
C4 ..> C5 : use

note bottom of C1
	Ledger protocol network
	Represent existing money system
	Used for balance settlements
end note

note bottom of C2
	Used for transporting the following information:
		*Packets of Interledger Protocol data
		*Information on the settling of outstanding balances
end note

note bottom of C4
	Provide end-to-end communication between sender and receiver
	Used for:
		*Defining the condition and fulfillment that are used on the Interledger Protocol layer
		*Grouping and retrying packets to achieve a desired outcome
		*Determining the effective exchange rate of a payment
		*Adapting to the speed at which packets can be sent, for what amounts
		*Encrypting and decrypting data
end note

note bottom of C5
	Provides for exchanging basic server details needed by a client to set up a STREAM connection.
	Intended for use by end-user applications.
end note
@enduml