@startuml
participant Sender as PA1
participant Connector as PA2
participant Connector as PA3
participant Receiver as PA4

PA1 -> PA2 : Prepare
PA2 -> PA3 : Prepare
PA3 --> PA2 : <font color=red> Reject
PA2 --> PA1 : <font color=red> Reject
@enduml